import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import clsx from "clsx";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bain & Company | Distance Calculation",
  description: "Generated by renato h. osaka",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "min-h-screen bg-gradient-to-b from-sky-100 to-white"
        )}
      >
        <Navbar />

        <main className="flex flex-col items-center justify-center h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
